name: "Pull Request Deploy"
description: "A github action to automate the deployment of pull requests"
branding:
  icon: "cloud"
  color: "blue"

inputs:
  context:
    description: Directory in the repository where the Dockerfile is located
    required: false
    default: .
  dockerfile:
    description: Path to the Dockerfile
    required: false
    default: Dockerfile
  exposed_port:
    description: Port to expose in the container
    required: true
  envs:
    description: Environment variables to pass to the container (multi-line string)
    required: false
  github_token:
    description: GitHub token to authenticate API requests
    required: true

secrets:
  HOST: ${{ secrets.HOST }}
  USERNAME: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}
  PORT: ${{ secrets.PORT }}

outputs:
  preview-url:
    description: "Preview URL"
    value: ${{ steps.deploy.outputs.preview-url }}

runs:
  using: 'composite'
  steps:
    - id: deploy
      name: Deploy Pull Request
      uses: appleboy/ssh-action@master
      env:
        CONTEXT: ${{ inputs.context }}
        DOCKERFILE: ${{ inputs.dockerfile }}
        EXPOSED_PORT: ${{ inputs.exposed_port }}
        ENVS: ${{ inputs.envs }}
        REPO_URL: ${{ github.event.repository.clone_url }}
        PR_ID: "pr_${{ github.event.repository.id }}_${{ github.event.number }}"
        PR_ACTION: ${{ github.event.action }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        PORT: ${{ secrets.PORT }}
      with:
        HOST: $HOST
        USERNAME: $USERNAME
        PASSWORD: $PASSWORD
        PORT: $PORT
        port: $PORT
        envs: CONTEXT, DOCKERFILE, EXPOSED_PORT, ENVS, REPO_URL, PR_ID, PR_ACTION, GITHUB_TOKEN
        script_stop: true
        script: |
          pr-deploy
